[

/*
define_type('makerator');
		define_tag('oncreate');
				!var_defined('__amScripts')								?	var('__amScripts')								=	array_unique;
				!var_defined('__amStyles')								?	var('__amStyles')								=	array_unique;
				
				
		/define_tag;
		
		define_tag('options'
		,	-opt='usecache'						,	-type	=	'boolean'
		,	-opt='minify'						,	-type	=	'boolean'
		,	-opt='compress'						,	-type	=	'boolean'
		,	-opt='refresh'						,	-type	=	'boolean'
		,	-opt='paths'							,	-type	=	'map'
		,	-opt='subdomains'					,	-type	=	'array'
		,	-opt='content_debug'			,	-type	=	'string'
		,	-opt='content_primary'			,	-type	=	'string'
		,	-opt='content_siteAdmin'				,	-type	=	'string'
		,	-opt='content_siteAdminToolbar'		,	-type	=	'string'
		,	-opt='content_siteTitle'				,	-type	=	'string'
		,	-opt='errorMessage'					,	-type	=	'string'
		,	-opt='json_data'						,	-type	=	'map'
		,	-opt='json_scripts'					,	-type	=	'array'
		,	-opt='navbar_config_multiLevel'		,	-type	=	'boolean'
		,	-opt='navbar_config_showHome'		,	-type	=	'boolean'
		,	-opt='pageID'						,	-type	=	'integer'
		,	-opt='pageName'						,	-type	=	'string'
		,	-opt='passwordDatabaseQueries'		,	-type	=	'string'
		,	-opt='passwordFileOperations'		,	-type	=	'string'
		,	-opt='passwordUploads'				,	-type	=	'string'
		,	-opt='site_webMaster'				,	-type	=	'string'
		,	-opt='tablePrefix'					,	-type	=	'string'
		,	-opt='template'						,	-type	=	'base'
		,	-opt='templating_templateModules'				,	-type	=	'array'
		,	-opt='templating_inlineJavascript'	,	-type	=	'set'
		,	-opt='templating_inlineJquery'		,	-type	=	'set'
		,	-opt='templating_trailingHtml'		,	-type	=	'string'
		,	-opt='usernameDatabaseQueries'		,	-type	=	'string'
		,	-opt='usernameFileOperations'		,	-type	=	'string'
		,	-opt='usernameUploads'				,	-type	=	'string'
		);
				!local_defined('usecache')						?	local('usecache'						=	boolean);
				!local_defined('minify')						?	local('minify'							=	boolean);
				!local_defined('compress')						?	local('compress'							=	boolean);
				!local_defined('refresh')						?	local('refresh'							=	boolean);
				!local_defined('paths')							?	local('paths'							=	map);
				!local_defined('subdomains')					?	local('subdomains'						=	array);
				!local_defined('content_debug')			?	local('content_debug'			=	string);
				!local_defined('content_primary')			?	local('content_primary'				=	string);
				!local_defined('content_siteAdmin')				?	local('content_siteAdmin'				=	string);
				!local_defined('content_siteAdminToolbar')		?	local('content_siteAdminToolbar'		=	string);
				!local_defined('content_siteTitle')				?	local('content_siteTitle'				=	string);
				!local_defined('errorMessage')					?	local('errorMessage'					=	string);
				!local_defined('json_data')						?	local('json_data'						=	map);
				!local_defined('json_scripts')					?	local('json_scripts'						=	array);
				!local_defined('navbar_config_multiLevel')		?	local('navbar_config_multiLevel'		=	boolean);
				!local_defined('navbar_config_showHome')		?	local('navbar_config_showHome'			=	boolean);
				!local_defined('pageID')							?	local('pageID'							=	integer);
				!local_defined('pageName')						?	local('pageName'							=	string);
				!local_defined('passwordDatabaseQueries')		?	local('passwordDatabaseQueries'			=	string);
				!local_defined('passwordFileOperations')			?	local('passwordFileOperations'			=	string);
				!local_defined('passwordUploads')				?	local('passwordUploads'					=	string);
				!local_defined('site_webMaster')				?	local('site_webMaster'					=	string);
				!local_defined('tablePrefix')					?	local('tablePrefix'						=	string);
				!local_defined('template')						?	local('template'							=	string);
				!local_defined('templating_templateModules')				?	local('templating_templateModules'					=	array);
				!local_defined('templating_inlineJavascript')	?	local('templating_inlineJavascript'		=	set);
				!local_defined('templating_inlineJquery')		?	local('templating_inlineJquery'			=	set);
				!local_defined('templating_trailingHtml')		?	local('templating_trailingHtml'			=	string);
				!local_defined('usernameDatabaseQueries')		?	local('usernameDatabaseQueries'			=	string);
				!local_defined('usernameFileOperations')			?	local('usernameFileOperations'			=	string);
				!local_defined('usernameUploads')				?	local('usernameUploads'					=	string);
				
				
		/define_tag;
		
		define_tag();
		
		/define_tag;
		,	-opt='listeratorValidationDataTypes'		=	array('Alpha'
													,	-opt='AlphaNumeric'
													,	-opt='Date'
													,	-opt='Decimal'
													,	-opt='Email'
													,	-opt='Integer'
													,	-opt='Numeric'
													,	-opt='Phone'
													,	-opt='SSN'
													,	-opt='URL'
													)
		,	-opt='listeratorValidationKeys'			=	array
		,	-opt='listeratorValidationTags'			=	map

/define_type;
*/
]